### ISSUE TITLE
Problems connecting with docker - DNS resolution

### ISSUE THREAD

**Issue by Ninerian** [leafclick/pgmig#2]
Hello, 

I tried to run `pgmig` with the given instructions for the docker container but where not able to build a connection. 

### Steps to reproduce: 

1. Create a docker-compose.yml with the following content
```yaml
version: '3'

services:
  db:
    container_name: maps_db
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev_maps
      POSTGRES_PASSWORD: dev_maps
      POSTGRES_DB: maps
    volumes:
      - maps-volume:/var/lib/postgresql/data

  pgmig:
    image: leafclick/pgmig:0.7.0
    environment:
      PGHOST: 127.0.0.1
      PGDATABASE: maps
      PGUSER: dev_maps
      PGPASSWORD: dev_maps
      RESOURCE_DIR: migrations
    volumes:
      - ./resources/migrations:/migrations
    depends_on:
      - db

volumes:
  maps-volume:
```

2. Start the db with `docker-compose up -d db`
3. Check that the db is running with `docker ps`
4. Test connect with `psql -h "127.0.0.1" -U dev_maps -d maps`
5. Try to init the database with `docker-compose run --rm pgmig init`
6. Try to init the database with 
   ```
	docker run -ti \                          
           --rm \
           --mount "type=bind,src=$PWD/resources/migrations,dst=/migrations" \
           -e PGHOST=127.0.0.1 \
           -e PGDATABASE=maps \
           -e PGUSER=dev_maps \
           -e PGPASSWORD=dev_maps \
           -e RESOURCE_DIR=migrations \
           leafclick/pgmig:0.7.0 init
   ```

### Expected behavior:
 
the database is created using the init.sql file

### Actual behavior: 

pgmig exits with the error:

<details>
<summary>Error with stacktrace</summary>

```
2021-10-05T21:20:56.635Z 6e7938cd57f3 ERROR [com.zaxxer.hikari.pool.HikariPool:595] - HikariPool-1 - Exception during pool initialization.
                                                                      com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine         PosixJavaThreads.java: 192
                                                                                  com.oracle.svm.core.thread.JavaThreads.threadStartRoutine              JavaThreads.java: 519
                                                                                                                       java.lang.Thread.run                   Thread.java: 834
                                                                                                    org.postgresql.Driver$ConnectThread.run                   Driver.java: 375
                                                                                                           org.postgresql.Driver.access$100                   Driver.java:  62
                                                                                                       org.postgresql.Driver.makeConnection                   Driver.java: 465
                                                                                                    org.postgresql.jdbc.PgConnection.<init>             PgConnection.java: 223
                                                                                       org.postgresql.core.ConnectionFactory.openConnection        ConnectionFactory.java:  51
                                                                            org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl    ConnectionFactoryImpl.java: 213
                                                                                    org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect    ConnectionFactoryImpl.java:  98
                                                                                                        org.postgresql.core.PGStream.<init>                 PGStream.java:  95
                                                                                                  org.postgresql.core.PGStream.createSocket                 PGStream.java: 231
                                                                                                                    java.net.Socket.connect                   Socket.java: 609
                                                                                                           java.net.SocksSocketImpl.connect          SocksSocketImpl.java: 392
                                                                                                   java.net.AbstractPlainSocketImpl.connect  AbstractPlainSocketImpl.java: 224
                                                                                          java.net.AbstractPlainSocketImpl.connectToAddress  AbstractPlainSocketImpl.java: 242
                                                                                                 java.net.AbstractPlainSocketImpl.doConnect  AbstractPlainSocketImpl.java: 399
                                                                                                     java.net.PlainSocketImpl.socketConnect           PlainSocketImpl.java    
com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V       JNIJavaCallWrappers.java    
        java.net.ConnectException: Connection refused (Connection refused)
org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Exception in thread "main" java.lang.RuntimeException: could not start [#'pgmig.db.store/db-spec] due to
        at mount.core$up$fn__3218.invoke(core.cljc:80)
        at mount.core$up.invokeStatic(core.cljc:80)
        at mount.core$up.invoke(core.cljc:78)
        at mount.core$bring.invokeStatic(core.cljc:247)
        at mount.core$start.invokeStatic(core.cljc:287)
        at mount.core$start.doInvoke(core.cljc:281)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at mount.core$start_with_args.invokeStatic(core.cljc:389)
        at mount.core$start_with_args.doInvoke(core.cljc:385)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at pgmig.main$start_app.invokeStatic(main.clj:171)
        at pgmig.main$_main.invokeStatic(main.clj:190)
        at pgmig.main$_main.doInvoke(main.clj:185)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at pgmig.main.main(Unknown Source)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at hikari_cp.core$make_datasource.invokeStatic(core.clj:210)
        at pgmig.db.store$fn__5806.invokeStatic(store.clj:29)
        at pgmig.db.store$fn__5806.invoke(store.clj:29)
        at mount.core$record_BANG_.invokeStatic(core.cljc:74)
        ... 15 more
Caused by: org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.Driver$ConnectThread.getResult(Driver.java:416)
        at org.postgresql.Driver.connect(Driver.java:271)
        at java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql.DriverManager.getConnection(DriverManager.java:228)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        ... 21 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:609)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.access$100(Driver.java:62)
        at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```
</details>

### Additional notes

- the jdbc parameter is not usable through the defaults for the other params and the `cond->` in the `db/store.clj`
- the long stack trace should be omitted and only the error message wrote stout

**Comment by katox** [comment]
Hi!

If you run it in the multi-container setup you need to ensure both run in the same docker network, then the pgmig container can access the other container by the container_name (or the actual IP address which is _not_ localhost from the pgmig container point of view).

The PGHOST should be given proper IP address or docker hostname within the named docker network.

**Comment by Ninerian** [comment]
Docker compose sets up a default network, which makes all services accessible. It doesn't work, if I set the `PGHOST` to the data base service name. Then the error is: 

``` 
java.net.UnknownHostException: db
org.postgresql.util.PSQLException: The connection attempt failed.
```

Also it doesn't work when I explicitly set a custom network.

**Comment by Ninerian** [comment]
Somehow the resolution of the docker service to the IP doesn't work. When I do 

```
export PGHOST=172.22.0.2
./pgmig init
```

the connection succeeds. 

Or when I omit the PGHOST variable and use `network_mode: host` I can connect with the ip `127.0.0.1`

**Comment by katox** [comment]
It seems that something was not quite right in the built docker image. I updated the dockerfile - can you please try to rebuild it if it fixes the DNS resolution for you?

**Comment by Ninerian** [comment]
I tested the master branch and it works now. 👍

**Comment by Ninerian** [comment]
@katox can you please make a new release with this changes?

**Comment by katox** [comment]
https://github.com/leafclick/pgmig/releases/tag/v0.7.1
